---
- name: Configure all nodes
  hosts: all
  become: true
  tasks:
    - name: Update and install base packages
      apt:
        update_cache: yes
        name:
          - vim
          - curl
          - net-tools
        state: present

- name: Configure bastion
  hosts: "{{ lookup('env', 'TAG') }}_bastion"
  become: true
  tasks:
    - name: Install and configure SSH jump host
      debug:
        msg: "Bastion node ready (manual SSH jump configuration as needed)"

- name: Configure proxy nodes
  hosts:
    - "{{ lookup('env', 'TAG') }}_proxy1"
    - "{{ lookup('env', 'TAG') }}_proxy2"
  become: true
  vars:
    vip_address: "192.168.42.100"
    interface: "eth0"  # ****
  tasks:
    - name: Install HAProxy and keepalived
      apt:
        name:
          - haproxy
          - keepalived
        state: present
        update_cache: yes

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

    - name: Configure keepalived
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: Restart keepalived

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

    - name: Restart keepalived
      service:
        name: keepalived
        state: restarted

- name: Configure service nodes
  hosts: "{{ lookup('env', 'TAG') }}_node[1:3]"
  become: true
  tasks:
    - name: Install Python HTTP server
      apt:
        name: python3
        state: present

    - name: Start simple HTTP server
      shell: nohup python3 -m http.server 6000 &
      args:
        chdir: /tmp
