- name: Wait for all nodes to be reachable
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH
      wait_for_connection:
        timeout: 300

- name: Gather facts 
  hosts: all
  gather_facts: yes

- name: Update HAProxy configuration and reload service
  hosts: proxy
  become: yes
  tasks:
    - name: Template the haproxy config
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      notify:
        - reload haproxy

  handlers:
    - name: reload haproxy
      service:
        name: haproxy
        state: reloaded

- name: Reconfigure newly deployed service nodes
  hosts: nodes
  become: yes
  tasks:
    - name: Install base packages (excluding Flask)
      apt:
        name:
          - python3
          - python3-pip
          - curl
          - vim
          - net-tools
          - snmpd
        state: present
        update_cache: yes

    - name: Install Flask using pip
      pip:
        name: flask
        executable: pip3

    - name: Install Gunicorn using pip
      pip:
        name: gunicorn
        executable: pip3

    - name: Allow Telegraf port (9103)
      ufw:
        rule: allow
        port: '9103'
        proto: tcp

    - name: Deploy Flask service code
      copy:
        src: service.py
        dest: /usr/local/bin/service.py
        mode: '0755'

    - name: Configure SNMP daemon
      template:
        src: templates/snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf
      notify:
        - restart snmpd

    - name: Ensure SNMP service is started and enabled
      service:
        name: snmpd
        state: started
        enabled: yes

    - name: Deploy systemd unit for Flask service
      template:
        src: templates/service.service.j2
        dest: /etc/systemd/system/service.service
      notify:
        - daemon-reload
        - restart flask
        - enable flask

    - name: Ensure necessary firewall ports are open (optional, if UFW is used)
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 5000  # Flask service
        - 161   # SNMP

    - name: Add InfluxData GPG key
      apt_key:
        url: https://repos.influxdata.com/influxdata-archive_compat.key
        state: present

    - name: Add InfluxData APT repository
      apt_repository:
        repo: deb https://repos.influxdata.com/ubuntu focal stable
        state: present
        filename: influxdata

    - name: Install Telegraf
      apt:
        name: telegraf
        state: present
        update_cache: yes

    - name: Configure Telegraf
      template:
        src: templates/telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf
      notify: restart telegraf

    - name: Enable and start Telegraf
      systemd:
        name: telegraf
        enabled: yes
        state: started

  handlers:
    - name: restart snmpd
      service:
        name: snmpd
        state: restarted

    - name: daemon-reload
      systemd:
        daemon_reload: yes

    - name: restart flask
      service:
        name: service
        state: restarted

    - name: enable flask
      service:
        name: service
        enabled: yes
        state: started

    - name: restart telegraf
      service:
        name: telegraf
        state: restarted    


